# Site Settings
title: Daniel Sørensen - About
url: 'http://'
baseurl: '' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
style: styles-6

#Profile information
name: Daniel Sørensen
tagline: Software Developer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'I graduated in 2015 from Aalborg University with a masters degree in Software Development. Since graduating I have been working at BAE Systems Applied Intelligence as a Java Backend developer. I am a hard working person that works well in a team and also individually. I am a flexible team player that is not afraid to ask questions when needed. I am motivated by results and love to learn new things and incorporate them into my daily work when possible. I have a special love for Java and Linux and hope to dive deeper into these domains in my future career.'

#sidebar links
email: dunit@protonmail.com
#phone: 61 18 82 35
#website: dunit.com #do not add http://
linkedin: danielbockersorensen
github: dunitgit
#twitter: '@dunittwitter'
#Update all the sections by editing the files inside _data folder.

# Tracker
# analytics:

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
